use_frameworks!

platform :ios, '9.0'

target 'GAEventTrackingFramework_Example' do
  pod 'GAEventTrackingFramework', :path => '../'

  target 'GAEventTrackingFramework_Tests' do
    inherit! :search_paths

    
  end
end
